import Head from 'next/head';
import Link from 'next/link';
import Banner from '../components/banner';
import Input from '../components/input';
import Todos from '../components/todos';

export default function Home() {
	return (
		<div className="max-w-680 mx-auto p-20 bg-green-100">
			<Head>
				<title>Todo App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<nav className="p-5 flex justify-between font-light text-sm border-b-2 border-green-200">
				<h1>
					My<span className="text-green-600">Todo</span>'s
				</h1>
				<Link href="/">LogIn</Link>
			</nav>

			<main className="">
				<Input />
				<Todos />
			</main>
		</div>
	);
}
