import Head from 'next/head';
import Link from 'next/link';
import Banner from '../components/banner';
import Input from '../components/input';
import Todos from '../components/todos';

export default function Home() {
	return (
		<div className="max-w-680 mx-auto p-5 m-20">
			<Head>
				<title>Todo App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<nav className="p-5 flex justify-end font-light text-sm">
				<Link href="/">LogIn</Link>
			</nav>

			<main>
        <Banner />
				<Input />
				<Todos />
			</main>
		</div>
	);
}
